import React, { useEffect, useState } from 'react';
import { apiClient } from '../api/client';
import { Download, FileText, FileSpreadsheet, Presentation, FileCode } from 'lucide-react';

export const Deliverables: React.FC = () => {
  const [deliverables, setDeliverables] = useState<any[]>([]);

  useEffect(() => {
    loadDeliverables();
  }, []);

  const loadDeliverables = async () => {
    try {
      const res = await apiClient.getDeliverables();
      setDeliverables(res.deliverables || []);
    } catch (err) {
      console.error(err);
    }
  };

  const getIcon = (filename: string) => {
    if (filename.endsWith('.docx')) return <FileText size={20} color="#38bdf8" />;
    if (filename.endsWith('.pptx')) return <Presentation size={20} color="#f59e0b" />;
    if (filename.endsWith('.xlsx')) return <FileSpreadsheet size={20} color="#10b981" />;
    return <FileCode size={20} color="#a855f7" />;
  };

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '20px' }}>
      <div className="enterprise-card">
        <div className="card-title">
          <span>Generated Industrial Deliverables Hub</span>
          <span className="badge badge-success">VERIFIED FILE GENERATOR</span>
        </div>
        <p style={{ color: '#94a3b8', fontSize: '0.88rem', marginBottom: '16px' }}>
          All `.docx` approval notes, `.pptx` management presentation slide decks, `.xlsx` spreadsheet reports, and `.txt` files generated by autonomous agents are stored locally and available for download.
        </p>

        <table className="data-table">
          <thead>
            <tr>
              <th>File Format</th>
              <th>Deliverable Filename</th>
              <th>Size</th>
              <th>Date Generated</th>
              <th>Download</th>
            </tr>
          </thead>
          <tbody>
            {deliverables.length > 0 ? (
              deliverables.map((d, idx) => (
                <tr key={idx}>
                  <td>{getIcon(d.filename)}</td>
                  <td style={{ fontWeight: 600, color: '#f8fafc' }}>{d.filename}</td>
                  <td>{Math.round(d.size_bytes / 1024)} KB</td>
                  <td>{d.modified}</td>
                  <td>
                    <a
                      href={apiClient.getDownloadUrl(d.filename)}
                      target="_blank"
                      rel="noreferrer"
                      style={{ background: '#38bdf8', color: '#0f172a', padding: '5px 12px', borderRadius: '4px', fontSize: '0.8rem', fontWeight: 600, textDecoration: 'none', display: 'inline-flex', alignItems: 'center', gap: '4px' }}
                    >
                      <Download size={14} /> Download
                    </a>
                  </td>
                </tr>
              ))
            ) : (
              <tr>
                <td colSpan={5} style={{ textAlign: 'center', padding: '20px', color: '#94a3b8' }}>
                  No generated deliverables yet. Run a workbench task or SIH demo scenario to create DOCX, PPTX, or XLSX files.
                </td>
              </tr>
            )}
          </tbody>
        </table>
      </div>
    </div>
  );
};
